# Generated by Django 4.0.5 on 2022-07-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='test',
            field=models.IntegerField(default='0'),
        ),
    ]
