# Generated by Django 3.1.3 on 2022-07-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Applied',
            field=models.CharField(default='Nothing', max_length=1000),
        ),
    ]
