# Generated by Django 4.0.5 on 2022-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_data_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Distance',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Salary',
        ),
        migrations.RemoveField(
            model_name='data',
            name='company',
        ),
        migrations.RemoveField(
            model_name='data',
            name='location',
        ),
        migrations.RemoveField(
            model_name='data',
            name='test',
        ),
        migrations.AddField(
            model_name='data',
            name='Company_Job',
            field=models.CharField(default='ApplyAway', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='Description',
            field=models.CharField(default='Great Company', max_length=10000),
        ),
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.CharField(default='www.error.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
