# Generated by Django 3.1.3 on 2022-07-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20220725_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='url',
            new_name='Url',
        ),
        migrations.AlterField(
            model_name='data',
            name='Notes',
            field=models.CharField(default='Nothing', max_length=10000),
        ),
    ]
