# Generated by Django 4.0.5 on 2022-07-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20220725_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user2',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
