# Generated by Django 4.0.5 on 2022-07-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_rename_company_job_data_company_data_job_data_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Company',
            field=models.CharField(default='ApplyAway', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Description',
            field=models.CharField(default='Great Company', max_length=100000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Job',
            field=models.CharField(default='Error', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(default='www.error.com', max_length=1000),
        ),
    ]
