# Generated by Django 4.0.5 on 2022-07-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_remove_data_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
