# Generated by Django 4.0.5 on 2022-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_data_company_alter_data_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Status',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
    ]
