# Generated by Django 3.1.3 on 2022-07-20 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_data_company_alter_data_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Applied',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='data',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
