# Generated by Django 3.1.3 on 2022-07-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20220725_0339'),
        ('demoapp', '0009_auto_20220725_0226'),
    ]

    operations = [
    ]
