# Generated by Django 3.1.3 on 2022-07-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_merge_20220725_1550'),
        ('demoapp', '0007_remove_data_status'),
    ]

    operations = [
    ]
