# Generated by Django 4.0.5 on 2022-08-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_merge_20220725_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Applied',
            field=models.CharField(default='missing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Company',
            field=models.CharField(default='missing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Description',
            field=models.CharField(default='missing', max_length=100000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Job',
            field=models.CharField(default='missing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Notes',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='Url',
            field=models.CharField(default='missing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.CharField(default='missing', max_length=100),
        ),
    ]
