# Generated by Django 4.0.5 on 2022-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_alter_data_applied_alter_data_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Website',
            field=models.CharField(default='missing', max_length=100),
        ),
    ]
